services:
  - type: web
    name: hualiang-admin
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    routes:
      - path: /
        destination: /index.html
